import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navigation } from "@/components/Navigation";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:
    "Leipzig Momentum Panel on Worker Characteristics, Experiences, and Behavior",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="px-4 bg-gray-100 ">
          <main className="w-full max-w-6xl mx-auto flex-col">
            <Navigation />
          </main>
        </div>

        <div className="flex min-h-screen px-4">
          <main className="flex min-h-screen w-full max-w-6xl mx-auto flex-col py-16">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
