import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import { Navigation } from "@/components/Navigation";
import "./globals.css";

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["200", "400", "600", "800"],
});

export const metadata: Metadata = {
  title:
    "Leipzig Momentum Panel on Worker Characteristics, Experiences, and Behavior",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firaSans.variable} antialiased`}>
        <div className="px-4 bg-lmp-gray1">
          <main className="w-full max-w-6xl mx-auto flex-col">
            <Navigation />
          </main>
        </div>

        <div className="flex min-h-screen px-4">
          <main className="flex min-h-screen w-full max-w-6xl mx-auto flex-col py-16">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
